### ISSUE TITLE
sharing

### ISSUE THREAD

**Issue by butonic** [owncloud/nexus#32]
- [x] rebase to get cs3 apis: https://github.com/owncloud/nexus/issues/33
- [x] phoenix sharing ui, design tracked in https://github.com/owncloud/phoenix/issues/583
- [x] reva: ocdavsvc
  - share information is stored by storage providers, eg ACLs in eos, posix or s3
  - the share provider is a cache that allows answering
    - [ ] "who shared what with me" and
    - [ ] "what did I share with others"
  - cache is implemented in a persistent key value store so it does not need to 'boot'
  - comment to reread sharing information from storage manually
